# Schema for the configuration files of the rating_app module.
rating_app.settings:
  type: config_object
  label: "rating_app settings"
  mapping:
    example:
      type: string
      label: "Example"
